@URL = http://localhost:8000
@AccessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwMUc3OVZLVFRNRkYzRk5UREpTOFRRM1QxWSIsImlhdCI6MTY1NzExNDU4NiwiZXhwIjoxNjU5NzA2NTg2LCJpc3MiOiJhYmx5LWlzc3VlciJ9.oaFf6sVh4jAUNdVqGKdZZeqlq1YYeF49Bkb6FUZQFV0

###
POST {{URL}}/api/auth/cellphone
Content-Type: application/json; charset=utf-8

{
    "phone": "01073413576"
}

###
POST {{URL}}/api/auth/cellphone/verify
Content-Type: application/json; charset=utf-8

{
    "verificationId": 9,
    "verificationCode": "163188"
}

###
POST {{URL}}/api/auth/sign-up
Content-Type: application/json; charset=utf-8

{
    "verificationId": 3,
    "email":"email@domain.com",
    "password":"123123",
    "name":"에이블리",
    "nickname":"가고싶어요",
    "phone":"01073413576"
}

###
POST {{URL}}/api/auth/sign-in
Content-Type: application/json; charset=utf-8

{
    "emailOrPhone": "01012345678",
    "password": "123123"
}

###
POST {{URL}}/api/auth/sign-in
Content-Type: application/json; charset=utf-8

{
    "emailOrPhone": "email@domain.com",
    "password": "123123"
}

###
GET {{URL}}/api/users/self
Content-Type: application/json; charset=utf-8
Authorization: Bearer {{AccessToken}}

{

}


###
PUT {{URL}}/api/users/self/password
Content-Type: application/json; charset=utf-8
Authorization: Bearer {{AccessToken}}

{
    "verificationId": 6,
    "password": "321321"
}


